# sample hyprlock.conf
# for more configuration options, refer https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock
#
# rendered text in all widgets supports pango markup (e.g. <b> or <i> tags)
# ref. https://wiki.hyprland.org/Hypr-Ecosystem/hyprlock/#general-remarks
#
# shortcuts to clear password buffer: ESC, Ctrl+U, Ctrl+Backspace
#
# you can get started by copying this config to ~/.config/hypr/hyprlock.conf
#

$font = JetBrainsMono Nerd Font

general {
    hide_cursor = false
}

# uncomment to enable fingerprint authentication
# auth {
#     fingerprint {
#         enabled = true
#         ready_message = Scan fingerprint to unlock
#         present_message = Scanning...
#         retry_delay = 250 # in milliseconds
#     }
# }

animations {
    enabled = false
    bezier = linear, 1, 1, 0, 0
    animation = fadeIn, 1, 5, linear
    animation = fadeOut, 1, 5, linear
    animation = inputFieldDots, 1, 2, linear
}

background {
    monitor =
    color = rgba(15, 15, 18, 0.5)
    path = screenshot
    blur_passes = 1
}

input-field {
    monitor =
    size = 50%, 10%
    outline_thickness = 1
    inner_color = rgba(15, 15, 18, 0)

    outer_color = rgba(15, 15, 18, 0)
    check_color = rgba(15, 15, 18, 0)
    fail_color = rgba(15, 15, 18, 0)

    font_color = rgba(140, 57, 1, 1)
    fade_on_empty = false
    rounding = 0

    font_family = $font
    placeholder_text = PASSWORD
    fail_text = $PAMFAIL

    # uncomment to use a letter instead of a dot to indicate the typed password
    dots_text_format = *
    dots_size = 96
    dots_spacing = 0.3

    # uncomment to use an input indicator that does not show the password length (similar to swaylock's input indicator)
    # hide_input = true

    halign = center
    valign = center
}

# MESSAGE
label {
    monitor =
    text = LOCKED
    color = rgba(255, 140, 50, 1)
    font_size = 96
    font_family = $font


    position = 0, -100
    halign = center
    valign = top
}

# TIME
label {
    monitor =
    text = cmd[update:1000] echo "<b><big> $(date +"%H:%M:%S") </big></b>"
    font_size = 14
    font_family = $font
    color = rgba(190, 81, 3, 1)

    position = -100, -6
    halign = right
    valign = top
}

# DATE
label {
    monitor =
    text = 
    font_size = 25
    font_family = $font
    position = -30, -150
    halign = right
    valign = top
}

label {
    monitor =
    text = 
    font_size = 24
    onclick = hyprctl switchxkblayout all next

    position = 250, -20
    halign = center
    valign = center
}